---
- name: login to OpenShift using provided token
  command: "oc login --insecure-skip-tls-verify=true --token {{ token }} {{ openshift_api_url }}"
  changed_when: False

- name: "make sure to use project {{ namespace }}"
  command: "oc project {{ namespace }}"
  register: project_exists
  ignore_errors: true

- name: create Thoth Core template
  command: oc create --save-config=true --namespace "{{ namespace  }}" \
    --filename https://raw.githubusercontent.com/thoth-station/core/master/openshift/template.yaml

- name: create Thoth Core secrets template
  command: oc create --save-config=true --namespace "{{ namespace  }}" \
    --filename https://raw.githubusercontent.com/thoth-station/core/master/openshift/secret-template.yaml

- name: create Thoth Core configmap template
  command: oc create --save-config=true --namespace "{{ namespace  }}" \
    --filename https://raw.githubusercontent.com/thoth-station/core/master/openshift/configmap-template.yaml

- name: create Thoth Core Deployment templates
  command: "oc create --save-config=true --namespace {{ namespace }} --filename {{ item }}"
  with_items:
    - https://raw.githubusercontent.com/thoth-station/user-api/master/openshift/deployment-template.yaml
    - https://raw.githubusercontent.com/thoth-station/result-api/master/openshift/deployment-template.yaml

- name: create Thoth Core CronJob templates
  command: oc create --save-config=true --namespace "{{ namespace  }}" --filename "{{ item }}"
  with_items:
    - https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/cronJob-template.yaml
    - https://raw.githubusercontent.com/thoth-station/graph-refresh-job/master/openshift/cronJob-template.yaml
    - https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/openshift/cronJob-template.yaml
    - https://raw.githubusercontent.com/thoth-station/cve-update-job/master/openshift/cronJob-template.yaml

- name: create Thoth Core BuildConfig templates
  command: oc create --save-config=true --namespace "{{ namespace  }}" --filename "{{ item }}" 
  with_items:
    - https://raw.githubusercontent.com/thoth-station/user-api/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/result-api/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/graph-refresh-job/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/package-extract/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/solver/master/openshift/buildConfig-template.yaml
    - https://raw.githubusercontent.com/thoth-station/cve-update-job/master/openshift/buildConfig-template.yaml

- name: create Thoth Core ImageStream templates
  command: oc create --save-config=true --namespace "{{ namespace  }}" --filename "{{ item }}"
  with_items:
    - https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/imageStream-template.yaml
    - https://raw.githubusercontent.com/thoth-station/graph-refresh-job/master/openshift/imageStream-template.yaml
    - https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/openshift/imageStream-template.yaml
    - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/imageStream-template.yaml
    - https://raw.githubusercontent.com/thoth-station/package-extract/master/openshift/imageStream-template.yaml
    - https://raw.githubusercontent.com/thoth-station/solver/master/openshift/imageStream-template.yaml
    - https://raw.githubusercontent.com/thoth-station/cve-update-job/master/openshift/imageStream-template.yaml
